aug:
  image_aug: true
  masked_language_model: true

backbone: vgg19_bn

cnn:
  hidden: 512
  ks:
    - [2, 2]
    - [2, 2]
    - [2, 1]
    - [2, 1]
    - [1, 1]
  pretrained: true
  ss:
    - [2, 2]
    - [2, 2]
    - [2, 1]
    - [2, 1]
    - [1, 1]

dataloader:
  num_workers: 1
  pin_memory: true

dataset:
  data_root: ./train_data/old_images/
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: hw
  train_annotation: rec_gt_train.txt
  valid_annotation: rec_gt_test.txt

device: cuda:0

optimizer:
  max_lr: 0.001
  pct_start: 0.1

predictor:
  beamsearch: false

pretrain: /kaggle/input/aaaaa/other/default/1/pretrain/vgg_transformer.pth
# pretrain: null
quiet: false

seq_modeling: transformer

trainer:
  batch_size: 16
  checkpoint: ./checkpoint/transformerocr_checkpoint.pth
  export: ./output_model/vgg_transformer.pth
  iters: 20000
  log: ./train.log
  metrics: 100
  print_every: 200
  valid_every: 100

transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1

vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~÷≥Φ± '
weights: /kaggle/input/aaaaa/other/default/1/pretrain/vgg_transformer.pth